export const GET_ORGANIZATIONS = "GET_ORGANIZATIONS";
export const USER_ORGANIZATION = "USER_ORGANIZATION";
export const GET_ORGANIZATION_STATUS = "GET_ORGANIZATION_STATUS";
export const DELETE_ORGANIZATION = "DELETE_ORGANIZATION";
export const ADD_ORGANIZATION = "ADD_ORGANIZATION";
export const UPDATE_ORGANIZATION = "UPDATE_ORGANIZATION";
export const GET_USER_ORGANIZATION = "GET_USER_ORGANIZATION";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const GET_USERS = "GET_USERS";
export const AUTH_ERROR = "AUTH_ERROR";

export const GET_ERRORS = "GET_ERRORS";
export const GET_MESSAGES = "GET_MESSAGES";
export const CREATE_MESSAGE = "CREATE_MESSAGE";

export const BASE_URL = process.env.REACT_APP_BASE_URL;
export const WS_URL = process.env.REACT_APP_WS_URL;

export const LIST_INVOICES = "LIST_INVOICES";
export const GET_INVOICES = "GET_INVOICES";
export const ADD_INVOICE = "ADD_INVOICE";
export const UPDATE_INVOICE = "UPDATE_INVOICE";
export const DELETE_INVOICE = "DELETE_INVOICE";

export const LIST_ITEMS = "LIST_ITEMS";
export const GET_ITEMS = "GET_ITEMS";
export const ADD_ITEM = "ADD_ITEM";
export const UPDATE_ITEM = "UPDATE_ITEM";
export const DELETE_ITEM = "DELETE_ITEM";
export const SEARCH_INVENTORY = "SEARCH_INVENTORY";
export const REFETCH_INVENTORY = "REFETCH_INVENTORY"

export const LIST_CUSTOMERS = "LIST_CUSTOMERS";
export const GET_CUSTOMERS = "GET_CUSTOMERS";
export const ADD_CUSTOMER = "ADD_CUSTOMER";
export const UPDATE_CUSTOMER = "UPDATE_CUSTOMER";
export const DELETE_CUSTOMER = "DELETE_CUSTOMER";
export const SEARCH_CUSTOMERS = "SEARCH_CUSTOMERS";

export const LIST_PRESCRIPTIONS = "LIST_PRESCRIPTIONS";
export const GET_PRESCRIPTIONS = "GET_PRESCRIPTIONS";
export const ADD_PRESCRIPTION = "ADD_PRESCRIPTION";
export const UPDATE_PRESCRIPTION = "UPDATE_PRESCRIPTION";
export const DELETE_PRESCRIPTION = "DELETE_PRESCRIPTION";

